### ISSUE TITLE
LoRa_GetRSSI and LoRa_GetSNR error

### ISSUE THREAD

**Issue by opus-meum** [stm32duino/I-NUCLEO-LRWAN1#19]
Hi, 

I have been trying without success to return RSSI and SNR stats from received packets. However, each time either the LoRa_GetRSSI() and LoRa_GetSNR() functions are called from the lora_driver.c library, the Modem_AT_Cmd() called within the functions returns AT_UART_LINK_ERROR.

Does anyone know why this might be the case? Are there some limitations on when these functions can be called? I have not been able to find anything in the ST, USI or Semtech documentation to shed any light on this.

Hardware:
2 x I-NUCLEO-LRWAN1 shields hosted by NUCLEO-L073RZ boards. Firmware is a minor variant of the PING PONG firmware to achieve local end node-end node comms.

Thanks in advance!

**Comment by fpistm** [comment]
Hi @opus-meum 
Sorry for the delay, I've been busy on other task and forgot this issue.

Looking at those functions: `Lora_GetRSSI()` and  `Lora_GetSNR()`, they are not exposed as an API.
So never tested. And agreed they do not work. In fact they are based on old AT commands set and removed since firmware 2.6:
https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1/blob/6b40a398003f6156f41942ad9179959f63d75c2b/preloaded_firmware/CHANGELOG.txt#L156

Since 2.6 version,  RSSI and SNR are available with `AT+STAT` command which is not implemented. 
![image](https://github.com/user-attachments/assets/20eecc4f-d1e1-4ea2-af70-b67ea2dba97e)

You probably have a fw version >= 2.6.0. You can check using `ATI` command with the bridge Serial example.
As stated by the README.md
https://github.com/stm32duino/I-NUCLEO-LRWAN1/blob/main/README.md#version
This library is based on STM32CubeExpansion_LRWAN_V1.1.2 driver, newer version doesn't implement this new command set so no update can be performed here.
